### ISSUE TITLE
Redux as common API

### ISSUE THREAD

**Issue by steida** [reasonml/reductive#11]
I suppose the best advantage of Redux is hook able API enabling plugins ecosystem. How would it be possible with Reason and without Redux? Thank you.

**Comment by rickyvetter** [comment]
Great question. `createStore` in redux accepts a second argument which is usually satisfied by using `createMiddleware` which under the hood composes an arbitrary number of functions passed to it.

All redux middleware essentially satisfies the `store => next => action => someReturnVal` API (where `next` is of type `action => someReturnVal`. This has really nice properties of being able to compose functions which will surround the updated state - so you can easily execute before and after an update with a single update.

This same composition is possible in reductive through the `enhancer` option arg in `Reductive.Store.create` - which essentially mimics that API with some small changes to make things more natural in Reason. The only thing that isn't provided is the `applyMiddleware` because Reason has some really nice function composition abilities built in. The current example of this is actually written in a really weird way (apologies - I will make the examples cleaner before closing this issue), but let's say you have `middleware1`, `middleware2`, and `middleware3` that you want to apply to reductive. You can create a chain with:

```reason
let myMiddlewares store next action =>
  middleware1 store (middleware2 store ((middleware3 store) next)) action;
```

which is written a little more readable as as:

```reason
let myMiddlewares store next =>
  middleware1 store @@
  middleware2 store @@
  middleware3 store @@
  next;
```

Again - this system can be applied to _any_ state management system. The huge advantage redux has is a community excited to write more middleware to work with that specific api. But if everything are simple functions then sharing should be very easy!

If this doesn't answer your question - let me know!

**Comment by steida** [comment]
Thank you. It reminds me why I refused Redux originally. I had a Redux like lib in Este, and I refused Redux because everything is function and functions are composable, but Abramov had good arguments because of JavaScript. Great I was correct in Reason language at least :-)

**Comment by rickyvetter** [comment]
Updated the middleware examples in #12. If you have any other questions feel free to open another issue :)
